### ISSUE TITLE
Swagger

### ISSUE THREAD

**Issue by EsadSimitcioglu** [EsadSimitcioglu/Taskin#2]
Generate an API documentation for your Restful services using OpenAPI (Swagger)

**Comment by saydemr** [comment]
I think @SadikhovEmin is very very suitable for this task. He is a talented CS student.

**Comment by EsadSimitcioglu** [comment]
Agreed

**Comment by sadikhovemin** [comment]
Thanks. I'll do my best.

**Comment by saydemr** [comment]
I'm working on it on branch swagger. Feel free to checkout and contribute. Please do not add anything related on main branch <3
