### ISSUE TITLE
Naming conventions

### ISSUE THREAD

**Issue by saydemr** [EsadSimitcioglu/Taskin#3]
I suppose upvoting and downvoting an answer is not convenient.

[Here](https://github.com/EsadSimitcioglu/Taskin-Project/blob/47607b351f210bc85694823f8cf6a38f805591cd/src/main/java/com/example/Taskin/Controller/AnswerController.java#L25) verbs should not be used in the path.

**Comment by EsadSimitcioglu** [comment]
I don't know the solution actually because if I didn't specify the increase or decrease it will be ambiguity. I'm open to any suggestions
