### ISSUE TITLE
User Entity ?

### ISSUE THREAD

**Issue by saydemr** [EsadSimitcioglu/Taskin#4]
Should user be another entity? Because documentation says 2 users. It seems like it is inside another table.

![image](https://user-images.githubusercontent.com/37012364/147415531-bed660f8-91f4-4aa8-af0f-3e29021cf49b.png)

**Comment by EsadSimitcioglu** [comment]
Actually I discuss this with emin and deniz in the school. I have no idea actually. What you say may be true if you think it's the way the teacher wants it

**Comment by saydemr** [comment]
Let's ask this to instructor.
