### ISSUE TITLE
QuestionTag 

### ISSUE THREAD

**Issue by saydemr** [EsadSimitcioglu/Taskin#6]
Repo, Controller and Service of the QuestionTag class is not implemented.

**Comment by EsadSimitcioglu** [comment]
Because we don't need to implement it. Is there a rule for that ?

**Comment by saydemr** [comment]
[Here ](https://github.com/EsadSimitcioglu/Taskin-Project/blob/47607b351f210bc85694823f8cf6a38f805591cd/src/main/java/com/example/Taskin/Controller/QuestionController.java#L26) we provide string as a question tag. But we have a QuestionTag class. So if we have one of them why do we need the other.  I didn't understand.

Here is the rules related. Tags is plural so I think we should send an arraylist of them ? No ?
![image](https://user-images.githubusercontent.com/37012364/147416851-8091b207-2d0b-47e3-ba17-79c98ed6be1d.png)
