### ISSUE TITLE
Misleading Naming Convention

### ISSUE THREAD

**Issue by saydemr** [EsadSimitcioglu/Taskin#7]
[This](https://github.com/EsadSimitcioglu/Taskin-Project/blob/47607b351f210bc85694823f8cf6a38f805591cd/src/main/java/com/example/Taskin/Service/QuestionService.java#L86) and [this](https://github.com/EsadSimitcioglu/Taskin-Project/blob/47607b351f210bc85694823f8cf6a38f805591cd/src/main/java/com/example/Taskin/Service/QuestionService.java#L81) methods should increase and decrease the vote of a question. Naming convention is not satisfied and should be changed.

**Comment by EsadSimitcioglu** [comment]
Okay but to what ?

**Comment by saydemr** [comment]
removeVoteFromQuestion and addVoteToQuestion maybe ?
