### ISSUE TITLE
@Postmapping missing URL 

### ISSUE THREAD

**Issue by sadikhovemin** [EsadSimitcioglu/Taskin#8]
I am not sure if  [this](https://github.com/EsadSimitcioglu/Taskin-Project/blob/b0f1e623c2d505a17b80ffff2df32cb40461d050/src/main/java/com/example/Taskin/Controller/QuestionController.java#L37) mapping is correct? Can you please check it?

**Comment by EsadSimitcioglu** [comment]
What is the problem ?

**Comment by saydemr** [comment]
No problem actually, I falsely thought that there should be a link e.g. @PostMapping(/questions) but it is already up there. Closing this...
